[theme]
base="dark"
primaryColor="#00a2ff"  # Soft blue for a modern look
backgroundColor="#1e1e1e"  # Dark gray for the main background
secondaryBackgroundColor="#2c2c2c"  # Slightly lighter gray for sidebar
textColor="#d4d4d4"  # Soft white for text for readability
font="sans serif"  # Modern, clean font

